### ISSUE TITLE
replace path.exist with fs.exist

### ISSUE THREAD

**Issue by ghost** [lexoyo/connect-fs#4]
On line 127, please replace the path.exist with fs.exist as path.exist do no longer work

**Comment by lexoyo** [comment]
A pull request would be even better but thank you for the fix, I will take it into account soon

**Comment by ghost** [comment]
I'm so sorry but I do not understand the concept of pull etc. full and I'm not sure how to do it proper :-)

**Comment by lexoyo** [comment]
This is a good occasion to learn something cool :))

A pull request is a way to propose code changes to the owner of a
repository (unifile in this case)

You can try to reproduce the 7 steps of this tutorial (the 8th is for me to
accept your pull request)
http://crunchify.com/how-to-fork-github-repository-create-pull-request-and-merge/

**Comment by ghost** [comment]
Hi Alex, 
I was trying it and the interesting part is that I figured out that this fix has already implemented according the history it was fixed 25.08.2014. and it also looks quite good on the repository file but if I download the npm it looks that is the wrong file inside...
Which version of npm it should be the last one? I got 0.1.1 
Or do I have to use the connect-fs2?
So strange ....
May you have an idea?

**Comment by ghost** [comment]
found my problem. Debug on connect-fs but the project had a reference to connect-fs2.
I did switch back to your version and I hope that I could fix now everything. Sorry for disturbing, but at least I could learn something new as I was ready to do a pull request :-)

**Comment by lexoyo** [comment]
No problem :) :octocat:
